#! /bin/sh
case "$1" in
start)
  bash /isodenv/scripts/lib/start-gsa.sh
  ;;
status)
  bash /isodenv/scripts/lib/status-gs.sh
  ;;
kill)
  sudo bash /isodenv/scripts/lib/gs-kill.sh
  ;;
restart)
  sudo bash /isodenv/scripts/lib/gs-kill.sh
  bash /isodenv/scripts/lib/start-gsa.sh
  ;;
start-ui)
  bash /isodenv/scripts/lib/gs-webui-start.sh
  ;;
kill-ui)
  sudo bash /isodenv/scripts/lib/gs-webui-stop.sh
  ;;
restart-ui)
  sudo bash /isodenv/scripts/lib/gs-webui-stop.sh
  bash /isodenv/scripts/lib/gs-webui-start.sh
  ;;
health-check)
  bash /isodenv/scripts/lib/health-check.sh
  ;;
deploy)
  bash /isodenv/scripts/deploy-script.sh
  ;;
*)
  echo "Usage: service gigaspaces {start|stop|restart|status|start-ui|kill-ui|restart-ui|health-check|deploy}" >&2
  exit 1
  ;;
esac
