#! /bin/sh
case "$1" in
start)
  bash /isodenv/scripts/lib/start_gsa.sh
  ;;
status)
  #bash /isodenv/scripts/lib/...
  echo "command does not work"
  ;;
kill)
  sudo bash /isodenv/scripts/lib/gscheck.sh
  ;;
restart)
  sudo bash /isodenv/scripts/lib/gscheck.sh
  bash /isodenv/scripts/lib/start_gsa.sh
  ;;
start-ui)
  bash /isodenv/scripts/lib/gs-webui-start.sh
  ;;
kill-ui)
  sudo bash /isodenv/scripts/lib/gs-webui-stop.sh
  ;;
restart-ui)
  sudo bash /isodenv/scripts/lib/gs-webui-stop.sh
  bash /isodenv/scripts/lib/gs-webui-start.sh
  ;;
health-check)
  bash /isodenv/scripts/lib/health_check.sh
  ;;
deploy-app)
  bash /isodenv/scripts/lib/deploy_script.sh
  ;;
*)
  echo "Usage: service gigaspaces {start|stop|restart|status|start-ui|kill-ui|restart-ui|health-check|deploy-app}" > &2
  exit 1
  ;;
esac
